package com.springboot.example.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodities
 */
public class Commodities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodities.fruit_id_
     *
     * @mbg.generated
     */
    private String fruitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodities.fruit_name_
     *
     * @mbg.generated
     */
    private String fruitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodities.price_
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodities.locality_
     *
     * @mbg.generated
     */
    private String locality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodities.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodities.fruit_id_
     *
     * @return the value of commodities.fruit_id_
     *
     * @mbg.generated
     */
    public String getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodities.fruit_id_
     *
     * @param fruitId the value for commodities.fruit_id_
     *
     * @mbg.generated
     */
    public void setFruitId(String fruitId) {
        this.fruitId = fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodities.fruit_name_
     *
     * @return the value of commodities.fruit_name_
     *
     * @mbg.generated
     */
    public String getFruitName() {
        return fruitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodities.fruit_name_
     *
     * @param fruitName the value for commodities.fruit_name_
     *
     * @mbg.generated
     */
    public void setFruitName(String fruitName) {
        this.fruitName = fruitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodities.price_
     *
     * @return the value of commodities.price_
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodities.price_
     *
     * @param price the value for commodities.price_
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodities.locality_
     *
     * @return the value of commodities.locality_
     *
     * @mbg.generated
     */
    public String getLocality() {
        return locality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodities.locality_
     *
     * @param locality the value for commodities.locality_
     *
     * @mbg.generated
     */
    public void setLocality(String locality) {
        this.locality = locality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodities.create_time_
     *
     * @return the value of commodities.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodities.create_time_
     *
     * @param createTime the value for commodities.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}