package com.springboot.example.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table contract
 */
public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_id_
     *
     * @mbg.generated
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.barcode_
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.type_
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.accessory_id_
     *
     * @mbg.generated
     */
    private String accessoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_id_
     *
     * @return the value of contract.contract_id_
     *
     * @mbg.generated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_id_
     *
     * @param contractId the value for contract.contract_id_
     *
     * @mbg.generated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.barcode_
     *
     * @return the value of contract.barcode_
     *
     * @mbg.generated
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.barcode_
     *
     * @param barcode the value for contract.barcode_
     *
     * @mbg.generated
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.type_
     *
     * @return the value of contract.type_
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.type_
     *
     * @param type the value for contract.type_
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.accessory_id_
     *
     * @return the value of contract.accessory_id_
     *
     * @mbg.generated
     */
    public String getAccessoryId() {
        return accessoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.accessory_id_
     *
     * @param accessoryId the value for contract.accessory_id_
     *
     * @mbg.generated
     */
    public void setAccessoryId(String accessoryId) {
        this.accessoryId = accessoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_time_
     *
     * @return the value of contract.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_time_
     *
     * @param createTime the value for contract.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}