package com.springboot.example.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table middle_tab
 */
public class MiddleTab {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_tab.middle_id_
     *
     * @mbg.generated
     */
    private String middleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_tab.contract_id_
     *
     * @mbg.generated
     */
    private String contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_tab.fruit_id_
     *
     * @mbg.generated
     */
    private String fruitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_tab.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_tab.middle_id_
     *
     * @return the value of middle_tab.middle_id_
     *
     * @mbg.generated
     */
    public String getMiddleId() {
        return middleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_tab.middle_id_
     *
     * @param middleId the value for middle_tab.middle_id_
     *
     * @mbg.generated
     */
    public void setMiddleId(String middleId) {
        this.middleId = middleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_tab.contract_id_
     *
     * @return the value of middle_tab.contract_id_
     *
     * @mbg.generated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_tab.contract_id_
     *
     * @param contractId the value for middle_tab.contract_id_
     *
     * @mbg.generated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_tab.fruit_id_
     *
     * @return the value of middle_tab.fruit_id_
     *
     * @mbg.generated
     */
    public String getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_tab.fruit_id_
     *
     * @param fruitId the value for middle_tab.fruit_id_
     *
     * @mbg.generated
     */
    public void setFruitId(String fruitId) {
        this.fruitId = fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_tab.number
     *
     * @return the value of middle_tab.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_tab.number
     *
     * @param number the value for middle_tab.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}