package com.springboot.example.mapper;

import com.springboot.example.model.Commodities;
import java.util.List;

public interface CommoditiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities
     *
     * @mbg.generated
     */
    int insert(Commodities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities
     *
     * @mbg.generated
     */
    Commodities selectByPrimaryKey(String fruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities
     *
     * @mbg.generated
     */
    List<Commodities> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodities
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Commodities record);
}