package com.springboot.example.mapper;

import com.springboot.example.model.MiddleTab;
import java.util.List;

public interface MiddleTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle_tab
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String middleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle_tab
     *
     * @mbg.generated
     */
    int insert(MiddleTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle_tab
     *
     * @mbg.generated
     */
    MiddleTab selectByPrimaryKey(String middleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle_tab
     *
     * @mbg.generated
     */
    List<MiddleTab> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table middle_tab
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiddleTab record);
}