package com.springboot.example.mapper;

import com.springboot.example.model.Retailer;
import java.util.List;

public interface RetailerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retailer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retailerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retailer
     *
     * @mbg.generated
     */
    int insert(Retailer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retailer
     *
     * @mbg.generated
     */
    Retailer selectByPrimaryKey(String retailerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retailer
     *
     * @mbg.generated
     */
    List<Retailer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retailer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Retailer record);
}